import { expect, test } from "vitest";
import { buildData } from "./data";
import { buildSchema } from "./schema";

const model = /* GraphQL */ `
  type User {
    name: String!
    profile: Profile
    class: Class!
    clubs: [Club!]!
  }

  type Profile {
    age: Int
  }

  type Class {
    name: String!
    users: [User!]!
  }

  type Club {
    name: String!
    users: [User!]!
  }
`;

test("buildData", () => {
  const schema = buildSchema(model);
  const data = buildData(schema);

  expect(data).toMatchInlineSnapshot(`
    [
      {
        "count": 3,
        "directives": {},
        "fields": [
          "id",
          "createdAt",
          "updatedAt",
          "name",
        ],
        "index": 0,
        "name": "Class",
        "values": [
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000000000001",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-1",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000000000002",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-2",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000000000003",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-3",
            },
          ],
        ],
      },
      {
        "count": 3,
        "directives": {},
        "fields": [
          "id",
          "createdAt",
          "updatedAt",
          "name",
        ],
        "index": 1,
        "name": "Club",
        "values": [
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000001",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-1",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000002",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-2",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000003",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-3",
            },
          ],
        ],
      },
      {
        "count": 9,
        "directives": {},
        "fields": [
          "id",
          "createdAt",
          "updatedAt",
          "age",
          "userId",
        ],
        "index": 2,
        "name": "Profile",
        "values": [
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000200000001",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000001",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000200000002",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000002",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000200000003",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000003",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000200000004",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000004",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000200000005",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000005",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000200000006",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000006",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000200000007",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000007",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000200000008",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000008",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000200000009",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000009",
            },
          ],
        ],
      },
      {
        "count": 9,
        "directives": {},
        "fields": [
          "id",
          "createdAt",
          "updatedAt",
          "classId",
          "name",
        ],
        "index": 3,
        "name": "User",
        "values": [
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000001",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000000000001",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-1",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000002",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000000000002",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-2",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000003",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000000000003",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-3",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000004",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000000000001",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-4",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000005",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000000000002",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-5",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000006",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000000000003",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-6",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000007",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000000000001",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-7",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000008",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000000000002",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-8",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000009",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000000000003",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-9",
            },
          ],
        ],
      },
      {
        "count": 27,
        "directives": {
          "join": {},
        },
        "fields": [
          "id",
          "createdAt",
          "updatedAt",
          "clubId",
          "userId",
        ],
        "index": 4,
        "name": "ClubToUser",
        "values": [
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000001",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000001",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000001",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000002",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000002",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000002",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000003",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000003",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000003",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000004",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000001",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000004",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000005",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000002",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000005",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000006",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000003",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000006",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000007",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000001",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000007",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000008",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000002",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000008",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000009",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000003",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000009",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000010",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000001",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000001",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000011",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000002",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000002",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000012",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000003",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000003",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000013",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000001",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000004",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000014",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000002",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000005",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000015",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000003",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000006",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000016",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000001",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000007",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000017",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000002",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000008",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000018",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000003",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000009",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000019",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000001",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000001",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000020",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000002",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000002",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000021",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000003",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000003",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000022",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000001",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000004",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000023",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000002",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000005",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000024",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000003",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000006",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000025",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000001",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000007",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000026",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000002",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000008",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000400000027",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000100000003",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "UUID",
              "value": "00000000-0000-4000-a000-000300000009",
            },
          ],
        ],
      },
    ]
  `);
});
